version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region il-central-1 | docker login --username AWS --password-stdin 937171232889.dkr.ecr.il-central-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t pro-beauty .
      - docker tag pro-beauty:latest 937171232889.dkr.ecr.il-central-1.amazonaws.com/pro-beauty:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 937171232889.dkr.ecr.il-central-1.amazonaws.com/pro-beauty:latest
      - printf '[{"name":"pro-beauty","imageUri":"%s"}]' 937171232889.dkr.ecr.il-central-1.amazonaws.com/pro-beauty:latest > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
